common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views


from django.conf import settings    # static
from django.conf.urls.static import static  # static 이미지 추가

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('security_portal/', include('security_portal.urls')), # '보안포털용
    path('', base_views.index, name='index'),   # '/' 에 해당되는 path
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),


    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),
]

security_portal/urls.py
from django.urls import path

from . import views

app_name = 'security_portal'

urlpatterns = [
    # 진원님 코드 추가하면서 주석처리
    # path('', views.index, name='index'),

    path('magazine_security/', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),

    # 진원님 코드 추가
    path('home/', views.home, name='home'),
    path('', views.home, name='home'),
    # 진원님 코드 종료
]

security_portal/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    image = models.ImageField(upload_to='images/', blank=True, null=True, default='images/no_img.jpg')
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="security_portal")
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    # modify_date = models.DateTimeField(null=True, blank=True)


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

security_portal/forms.py
from django import forms
from security_portal.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Question


def index(request):
    """
    pybo 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    # 조회

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}

    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


@login_required(login_url='common:login')
def question_create(request):
    """
    pybo 질문등록
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    pybo 질문수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    pybo 질문삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

security_portal/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator

# 진원님 코드 추가
def home(request):
    """
    pybo HOME 출력
    """
    return render(request, 'security_portal/home_ik.html')
# 진원님 코드 종료

def index(request):
    """
    security_portal 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지

    # 조회
    question_list = Question.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj}
    return render(request, 'security_portal/question_list.html', context)

def detail(request, question_id):
    """
    security_portal 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'security_portal/question_detail.html', context)

def answer_create(request, question_id):
    """
    security_portal 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('security_portal:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'security_portal/question_detail.html', context)

def question_create(request):
    """
    security_portal 질문등록
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('security_portal:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'security_portal/question_form.html', context)

templates/security_portal/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- 임교님 코드 추가-->
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <!-- Bootstrap icons-->
    <link rel="stylesheet" href="{% static 'bootstrap-icons.css' %}">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>SK Telink Security Potal</title>

    <style> div { text-align: center; } </style>
    <!-- 임교님 코드 종료-->
</head>


<body>

{% include "security_portal/navbar_ik.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- 임교님 코드 추가-->
<!-- Bootstrap core JS-->
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
<!-- Core theme JS-->
<script src="{% static 'scripts.js' %}"></script>
<!-- Footer-->
<footer class="py-3 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; ICT Security Team</p></div>
</footer>
<!-- 임교님 코드 종료-->

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->



</body>
</html>

templates/security_portal/base_ik.html
{% load static %}
<!doctype html>
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bottstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <!-- Bootstrap icons-->
    <link rel="stylesheet" href="{% static 'bootstrap-icons.css' %}">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>SK Telink Security Potal</title>

    <style> div { text-align: center; } </style>
</head>

<body class="pt-5">
<!-- include 기능을 이용하여 html 삽입할 수 있다 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- Bootstrap core JS-->
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
<!-- Core theme JS-->
<script src="{% static 'scripts.js' %}"></script>
<!-- Footer-->
<footer class="py-3 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; ICT Security Team</p></div>
</footer>

</body>
</html>

templates/security_portal/home_ik.html
{% extends 'security_portal/base.html' %}
{% block content %}
{% load static %}

<!-- Header-->
<header id="header" class="py-5">
    <div class="container px-lg-5">
        <div class="p-4 p-lg-10 bg-light rounded-3 text-center">
            <div class="m-4 m-lg-3">
                <h1 class="display-5 fw-bold">Welcom to Security Potal!</h1>
                <p class="fs-4">SK텔링크 보안포탈에 오신 것을 환영합니다</p>
            </div>
        </div>
    </div>
</header>

<div>
    <img src="{% static 'wall1.png' %}" alt="배경1" width="1200" class="img-responsive" style="margin:0 auto;">
</div>

<!-- Page Content-->
<section class="pt-5">
<div class="container px-lg-5">
    <!-- Page Features-->
    <div class="row gx-lg-5">
        <div class="col-lg-6 col-xxl-4 mb-5">
            <div class="card bg-light border-0 h-100">
                <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"> 1 </div>
                    <h2 class="fs-4 fw-bold"><a href="#rules1">정보보호 실천수칙</a></h2>
                    <p class="mb-0">비대면 시대 지켜야 할</p>
                    <p class="mb-0">정보보호 실천수칙(개인편)</p>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-xxl-4 mb-5">
            <div class="card bg-light border-0 h-100">
                <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"> 2 </div>
                    <h2 class="fs-4 fw-bold"><a href="#rules2">랜섬웨어 예방수칙</a></h2>
                    <p class="mb-0">나의 소중한 자료를 지키는</p>
                    <p class="mb-0">랜섬웨어 피해 예방 5대 수칙</p>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-xxl-4 mb-5">
            <div class="card bg-light border-0 h-100">
                <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"> 3 </div>
                    <h2 class="fs-4 fw-bold"><a href="#rules3">스마트폰 보안수칙</a></h2>
                    <p class="mb-0">일상에서 지켜주세요</p>
                    <p class="mb-0">스마트폰 보안수칙 10</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="rules1" style="padding:20px;">
    <img src="{% static 'rules1.jpg' %}" alt="정보보호 실천수칙" width="1200" class="img-responsive img-thumbnail" style="margin:0 auto;">
</div>

<div id="rules2" style="padding:20px;">
    <img src="{% static 'rules2.png' %}" alt="랜섬웨어 예방수칙" width="1200" class="img-responsive img-thumbnail" style="margin:0 auto;">
</div>

<div id="rules3" style="padding:20px;">
    <img src="{% static 'rules3.jpg' %}" alt="스마트폰 보안수칙" width="1200" class="img-responsive img-thumbnail" style="margin:0 auto;">
</div>

<div style="position: fixed; bottom: 20px; right: 50px;">
<a href="#header">TOP</a>
</div>

{% endblock %}

templates/security_portal/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'security_portal:index' %}">Security_Portal</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }}(로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

templates/security_portal/navbar_ik.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container px-lg-0">
        <a class="navbar-brand" href="{% url 'security_portal:home' %}">SKTL Security Potal</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    알림마당
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href="#">공지사항</a></li>
                    <li><a class="dropdown-item" href="#">자주하는 질문응답</a></li>
                    <li><a class="dropdown-item" href="#">개인정보 바로알기</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    지원마당
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href="#">방화벽 신청</a></li>
                    <li><a class="dropdown-item" href="#">IT지원요청서</a></li>
                    <li><a class="dropdown-item" href="#">보안 문의</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    자료마당
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href="../laws_data">법령자료</a></li>
                    <li><a class="dropdown-item" href="../regulation_data">지침자료</a></li>
                    <li><a class="dropdown-item" href="../SKTL_Policy">SK텔링크 정책</a></li>
                    <li><a class="dropdown-item" href="../GuideManual">가이드 및 매뉴얼</a></li>
                    <li><a class="dropdown-item" href="../Trend">최신동향</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    보안매거진
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'security_portal:index' %}">뉴스클리핑</a></li>
                    <li><a class="dropdown-item" href="#">이달의 보안소식</a></li>
                    <li><a class="dropdown-item" href="#">알기쉬운 보안용어</a></li>
                    <li><a class="dropdown-item" href="#">개인정보보호 영상</a></li>
                  </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/security_portal/question_detail.html
{% extends 'security_portal/base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'security_portal:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/security_portal/question_list.html
{% extends 'security_portal/base.html' %}
{% load security_portal_filter %}
{% block content %}

<div class="container my-3">
    <div class="row justify-content-between my-3">  <!-- 양쪽정렬 justify-content-between로 변경 -->
         <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
                <!--
                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
                -->
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
            </select>
        </div>
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table">
<!--        <thead>-->
<!--        <tr class="text-center thead-dark">-->
<!--            <th>번호</th>-->
<!--            <th>이미지</th>-->
<!--            <th style="sidth:50%">제목</th>-->
<!--        </tr>-->
<!--        </thead>-->
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td rowspan="3", valign="middle">
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td rowspan="3">
                <!이미지 링크 -->
<!--                {% if question.image %}-->
                <a href="{% url 'security_portal:detail' question.id %}"><img src="{{ question.image.url }}", width="300", height="200" ></a>
<!--                {% endif %}-->
<!--                <a href="{% url 'security_portal:detail' question.id %}"><img src="https://image.ahnlab.com/img_upload/kr/site/images2/info/img_info12.jpg", width="400", height="200"></a>-->
<!--                    <a href="{% url 'security_portal:detail' question.id %}"><img src="{{ question.image.url }}", width="400", height="200"></a>-->
            </td>
            <td class="text-left", colspan="2">
                <a href="{% url 'security_portal:detail' question.id %}">{{ question.subject }}</a>
<!--                {% if question.answer_set.count > 0 %}-->
<!--                 <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>-->
<!--                {% endif %}-->
            </td>
        </tr>
        <tr>
            <td class="text-left", colspan="2">
                {{ question.content }}
<!--                {% if question.answer_set.count > 0 %}-->
<!--                 <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>-->
<!--                {% endif %}-->
            </td>
        </tr>
        <tr>
            <td>{{ question.author.username }}</td> <!-- 글쓴이 추가 -->
            <td class="text-right">{{ question.create_date }}</td>
        </tr>

        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'security_portal:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}